version: '3.9'

services:
  app:
    container_name: app
    image: app:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file: .env
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - './src:/usr/src/app/src'
      - './database:/usr/src/app/database'
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: nestjs_boilerplate_db
    image: postgres:15
    environment:
      POSTGRES_DB: boilerplatedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  postgres-data: ~
